### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in /home/xxx/go/src/jankenpon/svelte/node_modules/svelte/package.json

### ISSUE THREAD

**Issue by kokizzu** [mgholam/svelte-multi-page-app#2]
not sure what's wrong, but after `npm install` and `npm run dev` it shows:

```

  Your application is ready~! 🚀

  - Local:      http://localhost:5000

────────────────── LOGS ──────────────────

[!] Error: Package subpath './compiler.js' is not defined by "exports" in /home/xxx/svelte/node_modules/svelte/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in /home/xxx/svelte/node_modules/svelte/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:449:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/xxx/svelte/node_modules/rollup-plugin-svelte/index.js:11:4)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)

```

**Comment by kokizzu** [comment]
nevermind, updating to newer version solved the issue
```
    "rollup-plugin-svelte": "^6.1.1",
```
